spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
cors:
  urls: ${CORS_URLS:http://localhost:3000,http://localhost:5173}

security:
  oauth2:
    resourceserver:
      jwt:
        jws-algorithms: RS512
        jwk-set-uri: https://idp.example.org/.well-known/jwks.json
        
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
jwt:

  secret: d24403c9b60c52ccbdca4cb66efc6e9898bbbd99db13caf24f5aa5bb9a06d1678ca79aa096c50de7b0ebe99ad7d1083ce0add43a9815ae7c48c73c69fd255f28
  token:
    validity: 3600000  # 1 hour in milliseconds