spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    show-sql: ${SPRING_JPA_SHOW_SQL}
cors:
  urls: ${CORS_URLS:http://localhost:3000,http://localhost:5173}

security:
  oauth2:
    resourceserver:
      jwt:
        jws-algorithms: RS512
        jwk-set-uri: https://idp.example.org/.well-known/jwks.json
        
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
jwt:
  secret: secretest_key #do I need some enviroment variables here ?
  token:
    validity: 3600000  # 1 hour in milliseconds