name: CI backend

on:
  pull_request:
    branches:
      - main

jobs:
  build-gradle-project:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Backend-API
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: "temurin"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build